import { FormEvent, useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { api } from '../lib/api';
import type { CoaTemplateKey, CompanyDto } from '@akuntask/shared';

export default function Onboarding(): JSX.Element {
  const [step, setStep] = useState(0);
  const [company, setCompany] = useState<CompanyDto | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const navigate = useNavigate();
  useEffect(() => { api.onboarding().then((c) => { setCompany(c); setStep(c.onboardingCompleted ? 3 : c.onboardingStep); }).catch((e) => setError(e.message)); }, []);
  if (!company) return <div className="p-8 text-center text-slate-500">Memuat onboarding…</div>;
  if (step >= 3 && company.onboardingCompleted) { navigate('/'); return <></>; }
  const save = async (fn: () => Promise<CompanyDto | unknown>, next: number) => { setLoading(true); setError(null); try { const x = await fn(); if (x && typeof x === 'object' && 'id' in x) setCompany(x as CompanyDto); setStep(next); } catch (e) { setError(e instanceof Error ? e.message : 'Gagal'); } finally { setLoading(false); } };
  return <div className="min-h-screen bg-slate-50 py-10 px-4"><main className="max-w-xl mx-auto bg-white border border-slate-200 rounded-xl p-6"><div className="text-sm text-slate-500 mb-4">Setup awal • Langkah {Math.min(step + 1, 3)} dari 3</div><h1 className="text-2xl font-semibold mb-1">Selamat datang di Akuntask</h1><p className="text-sm text-slate-500 mb-6">Selesaikan setup perusahaan sebelum transaksi pertama.</p>{error && <div className="p-3 mb-4 bg-red-50 text-red-700 rounded text-sm">{error}</div>}{step === 0 && <Profile company={company} loading={loading} onSave={(d) => save(() => api.onboardingProfile(d), 1)} />}{step === 1 && <Template loading={loading} onSave={(t) => save(() => api.onboardingTemplate(t), 2)} />}{step === 2 && <Warehouse loading={loading} onSave={(n,l) => save(async () => { await api.onboardingWarehouse(n,l); const r=await api.completeOnboarding(); setCompany(r.company); return r.company; }, 3)} />}</main></div>;
}
function Profile({ company, loading, onSave }: { company: CompanyDto; loading: boolean; onSave: (x: { name: string; npwp?: string; address?: string; phone?: string; email?: string; industry?: string }) => void }): JSX.Element { const [name,setName]=useState(company.name); const [industry,setIndustry]=useState(company.industry??''); const [npwp,setNpwp]=useState(company.npwp??''); const [address,setAddress]=useState(company.address??''); return <form onSubmit={(e:FormEvent)=>{e.preventDefault();onSave({name,industry,npwp,address});}} className="space-y-4"><label className="block text-sm">Nama perusahaan<input required value={name} onChange={e=>setName(e.target.value)} className="mt-1 w-full border rounded px-3 py-2"/></label><label className="block text-sm">Industri<select value={industry} onChange={e=>setIndustry(e.target.value)} className="mt-1 w-full border rounded px-3 py-2"><option value="">Pilih industri</option><option>Retail</option><option>Jasa</option><option>F&B</option><option>Manufaktur</option><option>Lainnya</option></select></label><label className="block text-sm">NPWP (opsional)<input value={npwp} onChange={e=>setNpwp(e.target.value)} className="mt-1 w-full border rounded px-3 py-2"/></label><label className="block text-sm">Alamat (opsional)<textarea value={address} onChange={e=>setAddress(e.target.value)} className="mt-1 w-full border rounded px-3 py-2"/></label><button disabled={loading} className="bg-brand-600 text-white px-4 py-2 rounded">Lanjut</button></form>; }
function Template({loading,onSave}:{loading:boolean;onSave:(t:CoaTemplateKey)=>void}):JSX.Element { const [t,setT]=useState<CoaTemplateKey>('PSAK_FULL'); return <form onSubmit={e=>{e.preventDefault();onSave(t);}} className="space-y-3"><p className="text-sm">Pilih template Chart of Accounts. Bisa dikustomisasi nanti.</p>{([['PSAK_FULL','PSAK Lengkap','Semua akun aset, liabilitas, ekuitas, pendapatan, beban'],['RETAIL','Retail','Fokus penjualan dan persediaan'],['SERVICE','Jasa','Tanpa akun persediaan dan HPP']] as const).map(([k,n,d])=><label key={k} className="block border rounded p-3 cursor-pointer"><input type="radio" checked={t===k} onChange={()=>setT(k)} /> <span className="ml-2 font-medium">{n}</span><span className="block ml-5 text-xs text-slate-500">{d}</span></label>)}<button disabled={loading} className="bg-brand-600 text-white px-4 py-2 rounded">Gunakan template</button></form>; }
function Warehouse({loading,onSave}:{loading:boolean;onSave:(n:string,l?:string)=>void}):JSX.Element { const [name,setName]=useState('Gudang Utama'); const [location,setLocation]=useState(''); return <form onSubmit={e=>{e.preventDefault();onSave(name,location);}} className="space-y-4"><p className="text-sm text-slate-600">Setup gudang pertama. Modul inventory lengkap tersedia pada Phase 3.</p><label className="block text-sm">Nama gudang<input required value={name} onChange={e=>setName(e.target.value)} className="mt-1 w-full border rounded px-3 py-2"/></label><label className="block text-sm">Lokasi (opsional)<input value={location} onChange={e=>setLocation(e.target.value)} className="mt-1 w-full border rounded px-3 py-2"/></label><button disabled={loading} className="bg-brand-600 text-white px-4 py-2 rounded">Selesai ke Dashboard</button></form>; }
